// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAkjc0LekQAcg3raVPS7dzVE7cTcK98Tk',
    appId: '1:72245604435:web:a65e3a1fcb03e9b06d56a6',
    messagingSenderId: '72245604435',
    projectId: 'musclelog-a3869',
    authDomain: 'musclelog-a3869.firebaseapp.com',
    storageBucket: 'musclelog-a3869.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbEZq3emwp3hRlzesWYc7N-MWmRr5sIlM',
    appId: '1:72245604435:android:d599ccce4539c4826d56a6',
    messagingSenderId: '72245604435',
    projectId: 'musclelog-a3869',
    storageBucket: 'musclelog-a3869.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ryDXGKF6azQyzcSxPLYTfcvF9Z3TKMs',
    appId: '1:72245604435:ios:1ca6f52e07f7e3d46d56a6',
    messagingSenderId: '72245604435',
    projectId: 'musclelog-a3869',
    storageBucket: 'musclelog-a3869.firebasestorage.app',
    iosBundleId: 'com.musclelog.ios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ryDXGKF6azQyzcSxPLYTfcvF9Z3TKMs',
    appId: '1:72245604435:ios:585767ecbb1632b76d56a6',
    messagingSenderId: '72245604435',
    projectId: 'musclelog-a3869',
    storageBucket: 'musclelog-a3869.firebasestorage.app',
    iosBundleId: 'com.example.musclelog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAkjc0LekQAcg3raVPS7dzVE7cTcK98Tk',
    appId: '1:72245604435:web:3e4ebd470e139e3d6d56a6',
    messagingSenderId: '72245604435',
    projectId: 'musclelog-a3869',
    authDomain: 'musclelog-a3869.firebaseapp.com',
    storageBucket: 'musclelog-a3869.firebasestorage.app',
  );

}